### PR TITLE
Fixing compilation on clang and new bindings

### PR DESCRIPTION
**Pull request by PBechon**

### CODE REVIEW

**Comment by PBechon** [comment]
The travis build actually succeded, the unit test failed.

**Comment by pierriko** [comment]
any particular reason why this test fails with your patchset ?
```
./build/test/test_bresenham --log_level=test_suite
Running 1 test case...
Entering test suite "const_string test"
Entering test suite "bresenham"
Entering test case "test_bresenham"
line 1 size = 11
line 2 size = 11
Check order 
Check the coordinate of some specific point
/home/pkoch/work/gladys/test/test_bresenham.cpp(46): error in "test_bresenham": check b == true failed [false != true]
Leaving test case "test_bresenham"; testing time: 497mks
Leaving test suite "bresenham"
Leaving test suite "const_string test"

*** 1 failure detected in test suite "const_string test"
```
cf. https://github.com/pierriko/gladys/commit/38aff232bae4e0a4819422237f514b61d5c15670

**Comment by PBechon** [comment]
The written test was 
```
b == ( l[5][0] == 3 && l[5][1] == 5 ) ;
```
Then the value of b was tested. This test was meaningless: b was not assigned only the old value of b was tested. This is probably a typo.
My patch set assign b. So this test was never properly run. I have no clue what this part of the code is supposed to do, so I don't know if this is problem with the test or with the code.

Do you want me to split this changeset in separate pull requests ? The other commits should have no issue.

**Comment by pierriko** [comment]
I can see that, we should see with Cyril, meanwhile we can comment out the test.
I'll merge everything tomorrow

**Comment by cyrobin** [comment]
Sorry I didn't react earlier, « kind of busy » writing my thesis.
Patrick is right, '==' is a typo, so behind is an old bug I wrote. Bresenham is a fast way to compute line. It's widely use to compute raytracing. 
http://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm

The test is mean to check a particular point P of the line (it should belong to the line). I didn't run the code, but looking at it « with fresh eyes » tells me that switching the '3' and '5' values (meant to be the coordinates of the point P) is probably the thing to do. Doing so, P's coordinates seem more coherent with the ones of 's' and 't' (the line joins 's' to 't'). 

Sorry for the incovenience, and thank you to spotted it out.

**Comment by cyrobin** [comment]
Ok, I've have a  fix, I will submit it.

**Comment by pierriko** [comment]
Merged. Thanks

**Pull request closed without merging**
